### ISSUE TITLE
How can change the ratio of the training set and the test set?

### ISSUE THREAD

**Issue by yitongshang2021** [clinicalml/TabLLM#28]
How can I change the ratio of the training set and the test set of the data? I changed the ratio from 0.2 to 0.3 in line 248 of t-few/src/data/dataset_readers.py
[data = orig_data.train_test_split(test_size=0.20, seed=self.config.seed)](https://github.com/clinicalml/TabLLM/blob/main/t-few/src/data/dataset_readers.py)
, but an error message appeared. The error message is:

Mark experiment t03b_heart_numshot4_seed42_ia3_pretrained100k as claimed
WARNING:root:Tried instantiating `DatasetTemplates` for heart heart_disease, but no prompts found. Please ignore this warning if you are creating new prompts for this dataset.
Using bfloat16 Automatic Mixed Precision (AMP)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
WARNING:datasets.arrow_dataset:Loading cached split indices for dataset at /root/TabLLM/datasets_serialized/heart/cache-942c41082140ee63.arrow and /root/TabLLM/datasets_serialized/heart/cache-9322ba60e8b03373.arrow
WARNING:datasets.arrow_dataset:Loading cached split indices for dataset at /root/TabLLM/datasets_serialized/heart/cache-5048afac3df1a668.arrow and /root/TabLLM/datasets_serialized/heart/cache-474f4783908dde0a.arrow
WARNING:datasets.fingerprint:Transform <function concatenate_datasets at 0x7f4628409158> couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.
WARNING:datasets.arrow_dataset:Loading cached processed dataset at /root/TabLLM/datasets_serialized/heart/cache-6dd7421f15e5b501.arrow
Traceback (most recent call last):
  File "/root/miniconda3/envs/tfew/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/miniconda3/envs/tfew/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/t-few/src/pl_train.py", line 86, in <module>
    main(config)
  File "/root/t-few/src/pl_train.py", line 57, in main
    trainer.fit(model, datamodule)
  File "/root/miniconda3/envs/tfew/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 741, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/root/miniconda3/envs/tfew/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/miniconda3/envs/tfew/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/root/miniconda3/envs/tfew/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1138, in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
  File "/root/miniconda3/envs/tfew/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1438, in _call_setup_hook
    self.datamodule.setup(stage=fn)
  File "/root/miniconda3/envs/tfew/lib/python3.7/site-packages/pytorch_lightning/core/datamodule.py", line 474, in wrapped_fn
    fn(*args, **kwargs)
  File "/root/t-few/src/data/data_module.py", line 28, in setup
    self.dev_dataset = self.dataset_reader.read_orig_dataset("validation")
  File "/root/t-few/src/data/dataset_readers.py", line 257, in read_orig_dataset
    orig_data = orig_data.add_column(name='idx', column=range(0, orig_data.num_rows))
  File "/root/miniconda3/envs/tfew/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 486, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/root/miniconda3/envs/tfew/lib/python3.7/site-packages/datasets/fingerprint.py", line 458, in wrapper
    out = func(self, *args, **kwargs)
  File "/root/miniconda3/envs/tfew/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 3590, in add_column
    table = concat_tables([dataset._data, column_table], axis=1)
  File "/root/miniconda3/envs/tfew/lib/python3.7/site-packages/datasets/table.py", line 1642, in concat_tables
    return ConcatenationTable.from_tables(tables, axis=axis)
  File "/root/miniconda3/envs/tfew/lib/python3.7/site-packages/datasets/table.py", line 1371, in from_tables
    return cls.from_blocks(blocks)
  File "/root/miniconda3/envs/tfew/lib/python3.7/site-packages/datasets/table.py", line 1319, in from_blocks
    table = cls._concat_blocks_horizontally_and_vertically(blocks)
  File "/root/miniconda3/envs/tfew/lib/python3.7/site-packages/datasets/table.py", line 1279, in _concat_blocks_horizontally_and_vertically
    pa_table_horizontally_concatenated = cls._concat_blocks(tables, axis=1)
  File "/root/miniconda3/envs/tfew/lib/python3.7/site-packages/datasets/table.py", line 1268, in _concat_blocks
    pa_table = pa_table.append_column(name, col)
  File "pyarrow/table.pxi", line 4619, in pyarrow.lib.Table.append_column
  File "pyarrow/table.pxi", line 4576, in pyarrow.lib.Table.add_column
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Added column's length must match table's length. Expected length 44 but got length 66

Can you give me some insightful suggestions? In addition, my ultimate goal is to test the training set that is not used for Few Shot Learning and get the label. So I used the above method to change the ratio of the training set and the test set. Do you have any suggestions on this? Very thanks!

**Comment by stefanhgm** [comment]
Hi @yitongshang2021,

Thanks for using TabLLM!

So, it seems the issue arises while reading the validation set:

```
File "/root/t-few/src/data/data_module.py", line 28, in setup
self.dev_dataset = self.dataset_reader.read_orig_dataset("validation")
```

And the specific error appears while adding an `idx` column. Maybe you can debug this line. It is a bit surprising that the number of rows `orig_data.num_rows` does not match the actual number of rows of `orig_data`.

```
File "/root/t-few/src/data/dataset_readers.py", line 257, in read_orig_dataset
orig_data = orig_data.add_column(name='idx', column=range(0, orig_data.num_rows))
```

Maybe the problem is caused by a cached dataset. You could try to clean `/root/TabLLM/datasets_serialized/heart/cache-*`.

Hope that helps a bit!
Stefan
